### ISSUE TITLE
[Metadata Enhancement]

### ISSUE THREAD

**Issue by Goldenfreddy0703** [doko-desuka/plugin.video.wsbeta#1]
Hey their sorry for bothering you but is there anyway you could make an enhancement to the addon? On the WonderfulSubs Beta website, The meta data and artwork is not as good and im looking for an addon that has a good veiw of everything. Im looking for an addon which shows the ratings, metadata, fanart, descriptions, eposode fanart, and unique titles fanart. Im looking for something that matches the hummingbird anime addon and your 3rd party addon is amazing, Is there anyway to add Meta data and artwork in this addon?
Here is a few examples that would be amazing to have on your addon.
![Capture 1](https://user-images.githubusercontent.com/62456796/80344682-fa2b3000-8835-11ea-92c5-36a0e8d8bc26.PNG)
![image](https://user-images.githubusercontent.com/62456796/80345015-77ef3b80-8836-11ea-840e-b322631037b6.png)
![Capture 3](https://user-images.githubusercontent.com/62456796/80344679-f8616c80-8835-11ea-9678-8e48357f1b21.PNG)

**Comment by doko-desuka** [comment]
@Goldenfreddy0703 hi. I like the concept behind Hummingbird, it searches on several sources. One of those sources is WonderfulSubs.

If it already shows the metadata you need, is there a reason why you're not using Hummingbird already?

**Comment by Goldenfreddy0703** [comment]
Hey, thank you so much for responding to my post, the main reason why I am not using the Hummingbird addon is because it’s not working anymore. The developer has not responded for 17 days and I’ve been responding to people that have issues with the addon. I said that the dev was busy and stuff, but I do not know what happened to the dev. Your 3rd party application is amazing and this Metadata, this could be the number one anima addon for wonderfulsubs. The old wonderfulsub addon that got deprecated does work and has a little bit of metadata but it’s really slow and most of the servers are not working but your addon does. I see potential in the addon and with the metadata and fanart like what hummingbird has could possibly be the number one addon for anime..

**Comment by doko-desuka** [comment]
To me only the `CR` source works, the `FA` source only works depending on your geographical location, or if you use a VPN for a country like the US.  

Where are those screenshots from?

**Comment by Goldenfreddy0703** [comment]
I actually took them and I have a advanced user interface called auramod and I wanted it to have a Netflix feel to it to make it professional and amazing at the same time. What i did is I used the hummingbird addon becouse the artwork or metadata is working, just not the playback and then I configured it with the interface to make it professional and clean and good.

**Comment by doko-desuka** [comment]
Based on what you're telling me, it'd make more sense to try and fix Hummingbird, a swiss army-knife type add-on, than to add metadata to WSBeta which is supposed to be a lightweight add-on built for slower devices.  

I don't know when I can take a look at Hummingbird, but I promise I will.  
If you have any other questions you can still comment in this thread (even though it's closed).

**Comment by Goldenfreddy0703** [comment]
Ok thank you man and thank you for the support.
